[package]
name = "query-noir"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[[bin]]
name = "query-noir"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.29.0", features = ["bundled", "uuid"] }
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-rustls" ] }
simplecrypt = "1.0.2"
anyhow = "1.0.71"
log = "0.4.19"
env_logger = "0.10.0"
rand = "0.8.5"
thiserror = "1.0.40"
uuid = { version = "1.3.4", features = [ "v4", "fast-rng", "serde" ] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
sql_lexer = "0.9.4"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
