volumes:
  mysql:
  psql:

services:
  mysql:
    image: mysql:8.0.29-debian
    container_name: mysql
    command: >
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: world # https://dev.mysql.com/doc/world-x-setup/en/world-x-setup-installation.html
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./dev/mysql/mysql.conf:/etc/mysql/conf.d/mysql.conf
      # extract in dev/mysql folder before mounting
      - ./dev/mysql/world.sql:/docker-entrypoint-initdb.d/world.sql:ro
  psql:
    image: postgres:16-bookworm
    container_name: psql
    command: >
      -c log_statement=all 
      -c ssl=on 
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem 
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      -c ssl_ca_file=/etc/ssl/certs/ce275665.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dvdrental # https://www.postgresqltutorial.com/postgresql-getting-started/postgresql-sample-database/
    volumes:
      - psql:/var/lib/postgresql/data
      - ./dev/psql/postgres.conf:/etc/postgresql/postgresql.conf
      # extract in dev/psql folder before mounting
      - ./dev/psql/dvdrental.tar:/tmp/dvdrental.tar
      - ./dev/psql/init.sh:/docker-entrypoint-initdb.d/init.sh 
    ports:
      - 5432:5432
