volumes:
  # mysql:
  psql:

services:
  # mysql:
  #   image: mysql:8.0.33
  #   container_name: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: world_x # https://dev.mysql.com/doc/world-x-setup/en/world-x-setup-installation.html
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql:/var/lib/mysql
  #     - ./dev/:/docker-entrypoint-initdb.d
  psql:
    image: postgres:15
    container_name: psql
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dvdrental # https://www.postgresqltutorial.com/postgresql-getting-started/postgresql-sample-database/
    volumes:
      - psql:/var/lib/postgresql/data
      # - ./db.tar:/tmp/db.tar // pg_restore -U postgres -d dvdrental -1 /tmp/db.tar
    ports:
      - 5432:5432
